### ISSUE TITLE
Add express examples for remaining express functions

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny#1080]
## How To

Check off an example when you start working on it and push directly to this branch with each update.

* Examples are in `shiny/api-examples`
* Examples should be named `app-express.py` (or `app-{more-descriptive-name}-express.py`)
* If no example is needed for express use `@no_example("express")` before (below) `@add_example()` to suppress errors.
  ```python
  from ._docstring import add_example, no_example_express

  @add_example()
  @no_example("express")
  def thing_in_core():
      ...
  ```

## Todo

- [ ] Remove the early exit in `docs._renderer.check_if_missing_expected_example` so that it will error if a function is added to the Express docs that doesn't have an example.

## Remaining Apps to Translate

- [x] accordion
- [x] accordion_panel
- [x] as_fillable_container
- [x] as_fill_item
- [x] card
- [ ] ~card_body~
- [x] card_footer
- [x] card_header
- [x] close
- [x] data_frame
- [x] download
- [x] download_button
- [ ] ~download_link~
- [x] dynamic_route
- [x] event
- [x] extended_task
- [x] file_reader
- [x] include_css
- [x] include_js
- [x] insert_accordion_panel
- [x] insert_ui
- [x] modal
- [x] navset_hidden
- [x] nav_panel
- [x] notification_show
- [x] on_ended
- [x] on_flush
- [x] on_flushed
- [x] output_image
- [x] output_plot
- [x] output_table
- [x] output_text
- [ ] ~output_transformer~
- [x] output_ui
- [x] page_fixed
- [x] page_fluid
- [x] panel_title
- [x] poll
- [x] popover
- [x] remove_accordion_panel
- [x] remove_ui
- [x] Renderer
- [x] req
- [ ] ~row~
- [x] SafeException
- [x] send_custom_message
- [ ] ~showcase_bottom~
- [ ] ~showcase_left_center~
- [ ] ~showcase_top_right~
- [x] SilentCancelOutputException
- [x] SilentException
- [x] tooltip
- [x] update_accordion
- [x] update_accordion_panel
- [x] update_action_button
- [x] update_checkbox
- [x] update_checkbox_group
- [x] update_date
- [x] update_date_range
- [x] update_navs
- [x] update_numeric
- [x] update_popover
- [x] update_radio_buttons
- [x] update_select
- [x] update_selectize
- [x] update_sidebar
- [x] update_slider
- [x] update_text
- [x] update_tooltip
- [x] value_box
