### ISSUE TITLE
Epic -- Data frames

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny#1119]
##  From #1198
- [x] Adds feature of getting selected data from dataframe renderer. ; mydf.data_selected_rows()
- [x] Adds feature of getting data from dataframe renderer. ; mydf.data()

## Followup to #1198
- [x] Split `mode` into `selection_mode` and `editable`; Throw error when `selection_mode` != `None` and `editable` == True; Add structure types for selection_mode.  (#1248)

## QA

* [ ] Round 1 (https://github.com/posit-dev/py-shiny/issues/1268)
* [x] Remove success animation, jumpy edit cells, broken click on edited cell (#1283)
* [x] Next sorted row when data frame is sorted (#1291)

## Features

- [x] Raw HTML in data grid. (https://github.com/posit-dev/py-shiny/issues/1117)
- [ ] Make examples for release
- [x] Content Editable cells (https://github.com/posit-dev/py-shiny/pull/1198)
- [x] Programmatically change selected rows (https://github.com/posit-dev/py-shiny/issues/1116)
- [x] ~~Add selected_rows method (https://github.com/posit-dev/py-shiny/issues/1120)~~
    - [x] ~~Make work in modules~~
    - [x] ~~Revisit input name `.input_selected_rows()`?~~
    - [x] ~~Fix documentation of types for return value (`None` vs empty tuple)~~
    - [x] Replace with `.input_cell_selection()`, `.update_cell_selection()`; (#1248)
- [x] Data grid fill/fillable (https://github.com/posit-dev/py-shiny/issues/1118)
- Enhancements to `@render.data_frame`
	- [x] `.cell_patches()`: Returns `list[{row_index: int, col_index: int, value: str}]` (#1198)
	- [x]  `.data()`: Currently returns `pd.DataFrame` (#1198)
	- [x] `.data_patched()`: Returns `.data()` with any manual edits (#1198)
	- [x] `.selection_modes()`: Returns value's `selection_modes=`  (#1198)
	- [x] `.input_cell_selection()`:  Takes some form of `{type: "row" | "col" | "region" | "cell" | "none", rows: tuple[int, ...] | tuple[int, int] | tuple[int], cols: tuple[int, ...] | tuple[int, int] | tuple[int]}` (#1248)
	- [x] `.update_cell_selection()`; Takes same value as `.input_cell_selection()` or some form of `"all" | "none" | {rows: int | tuple[int, int], cols: int | tuple[int, int]}` (#1248)
	- [x] `.data_selected()`; Returns `.data_patched()` subsetted to `.input_cell_selection()` (#1198)
	- [x] `.set_patch_fn()`; `.set_patches_fn()`; Decorators to set method to handle cell edits (patches)  (#1198)
	- [x] `.input_current_cell()`; `.update_current_cell()` ; Methods to set currently selected cell
- [x] Cell selection
	- [x] Retrieve selected cells: `mydf.input_cell_selection()`; Returns list of type,rows,columns information; (#1248)
	- [x] Update selected cells: `mydf.update_cell_selection()`; (#1248)
	- Types of selection:
		- [x] None; (#1248)
		- [x] Row; (#1248)
		- [ ] Column
		- [ ] Region
		- [ ] Cell
		- [ ] _all_ via given selection mode types
- Appearance
	- [x] Text area within editing (https://github.com/posit-dev/py-shiny/pull/1278)
- [ ] Copy / paste table selection
- [x] Consolidate data methods into a single data method. Currently too many `.data_*()` methods. 
	* Instead have a `.data_gen(*, selected=False, filtered=False, edited=False, ....)` method that returns a reactive value generator? 
	* Or single reactive value? Maybe given the inputs, it returns a cached version of the reactive calculations. This seems much more user friendly.
	* Related: https://github.com/posit-dev/py-shiny/issues/1240

**Editable tables**
- [x] Edit cells
	- [x] Server side tweak for cell / cells; `.set_patch_fn()`; `.set_patches_fn()`
- [ ] Add rows
- [ ] Add columns
- [ ] Paste data

**Styling**
- [ ] Styled tables
	- [x] DataGrid/DataTable `styles=` takes `Styles`
		- [ ] `Styles = list[StyleInfo]`
		- [ ] `StyleInfo = {loc: "body", rows: int | List[int], columns: int | str | List[int | str], style: str? | dict[str, Jsonifiable]? | None, class_: str | None, }`
	- [x] DataGrid/DataTable `styles=` takes `Callable[[data], Styles]`
	- [x] Call styles after edit and init. Send whole styles value
	- [ ] Support `Styles.rows: List[bool]`?
    - Post-1.0
	    - [ ] GT: Styling
	        - [ ] GT: Body cells [P0]
	        - [ ] GT: Column labels [P2]
	        - [ ] GT: Row labels (stubs) [P2]
	    - [ ] GT: cell data formatting [P0]
	        - [ ] GT: Sorting/filtering/editing on underlying data instead of displayed data [P1]
	    - [ ] GT: Column rearranging/hiding [P1]
	    - [ ] GT: Column names [P1]
	    - [ ] GT: Markdown/HTML support [P1]
	    - [ ] GT: Some amount of erroring if you used a GT feature we don't support [P1]
        - [ ] GT: Column alignment/width
        - [ ] GT: Table options?
        - [ ] GT: Font stack?
        - [ ] GT: Spanners
        - [ ] data view styles?
- [ ] Column widths
- [ ] Conditional formatting
- [ ] Great tables integration - documentation on website, and work with `render.table`
- [ ] Better handling of long entries (wrapping, truncating etc)

**Other**
- [ ] More generic data frame types: Ex: polars
- [ ] Server side rendering
- [x] Filtered view (#1240)
- [x] Keyboard shortcuts for improved navigation and selection

**Comment by schloerke** [comment]
Closing in favor of #1639
