### ISSUE TITLE
Epic -- JavaScript Components

### ISSUE THREAD

**Issue by icarusz** [posit-dev/py-shiny#1227]
Framing - we are trying to “complete” this in a minimal acceptable way - avoiding too much expansion

- [ ] Need to cover more frameworks (nice-to-have)
- [ ] Need output examples (currently only input)
- [ ] Inlining a JavaScript component into your app
- [ ] Update Docs
