### ISSUE TITLE
Epic -- ChatSQL

### ISSUE THREAD

**Issue by jcheng5** [posit-dev/py-shiny#1640]
- [ ] Extract module from the example app
- [ ] Make the module a template
- [ ] Logging
- [ ] Think about how to use different chat SDKs/APIs
- [ ] R version: streaming and tool calling

**Comment by cpsievert** [comment]
This is now available as https://github.com/posit-dev/querychat
