### ISSUE TITLE
Updated nav/navset API names

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/py-shiny#492]
In rstudio/bslib#546, we renamed many of the `nav_*()` and `navset_*()` functions in the R API. Many of these now align with the Python naming, but there are some notable differences. Here's a summary table:

| bslib (new) | Python (current) | Changes? |
|:--|:--|:-:|
| `nav_panel()` | [ui.nav](https://shiny.rstudio.com/py/api/ui.nav.html) | 👀 |
| `nav_panel_hidden()` | ui.nav_content | 👀 ❗ |
| `navset_tab()` | [ui.navset_tab](https://shiny.rstudio.com/py/api/ui.navset_tab.html) | |
| `navset_pill()` | [ui.navset_pill](https://shiny.rstudio.com/py/api/ui.navset_pill.html) |
| `navset_pill_list()` | [ui.navset_pill_list](https://shiny.rstudio.com/py/api/ui.navset_pill_list.html) | |
| `navset_hidden()` | ui.navset_hidden | ❗ |
| `navset_bar()` | ui.navset_bar | ❗ |
| `navset_card_tab()` | [ui.navset_tab_card](https://shiny.rstudio.com/py/api/ui.navset_tab_card.html) | 👀 |
| `navset_card_pill()` | [ui.navset_pill_card](https://shiny.rstudio.com/py/api/ui.navset_pill_card.html) | 👀 |

👀 new R name is different from current Python
❗ not in API refs

Note that this research also uncovered that `ui.navset_bar` and `ui.navset_tab_card` are exported but don't appear in [the API reference](https://shiny.rstudio.com/py/api).
```[tasklist]
### Tasks
- [x] `navset_pill_card` -> `navset_card_pill`
- [x] `navset_tab_card` -> `navset_card_tab`
- [x] ~~`nav_content` -> `nav_panel_hidden`~~
- [ ] `nav` -> `nav_panel`
- [x] document `navset_bar`
- [x] document `navset_hidden`
- [x] ~~document `nav_panel_hidden`~~
```

**Comment by schloerke** [comment]
`nav_content` -> `nav_panel_hidden` will not happen as `nav_content` was removed in #136

**Comment by schloerke** [comment]
@gadenbuie Would you be ok with leaving `nav` in py-shiny? This change would not be an easy transition.

Current methods (including deprecated methods):
```
>>> shiny.ui.n<TAB>
shiny.ui.nav(                 shiny.ui.navset_card_pill(    shiny.ui.navset_pill_list(   
shiny.ui.nav_control(         shiny.ui.navset_card_tab(     shiny.ui.navset_tab(         
shiny.ui.nav_menu(            shiny.ui.navset_hidden(       shiny.ui.navset_tab_card(    
shiny.ui.nav_spacer()         shiny.ui.navset_pill(         shiny.ui.notification_remove(
shiny.ui.navset_bar(          shiny.ui.navset_pill_card(    shiny.ui.notification_show(  
```

**Comment by cpsievert** [comment]
Reopening this as I think we should consider having a `nav_panel()` alias for `nav()` (and possibly deprecating the latter)

**Comment by wch** [comment]
I also prefer `nav_panel` to `nav`.
