### ISSUE TITLE
Move value_box from experimental to main

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny#710]
We would like to move value boxes, popovers, and tool tips to main with the following changes:

- [ ] Value boxes, but don't expose `showcase_layout`
- [ ] Tooltips, but don't expose `options`
- [ ] Popovers but don't expose `options`

**Comment by cpsievert** [comment]
Can be closed now?
